### ISSUE TITLE
Exception while Executing Operation

### ISSUE THREAD

**Issue by finch-wren** [adobe/pdfservices-python-sdk-samples#4]
All the validations are passed, so I am guessing it's not because of the file itself. 
My Code
```
def extract(file_name, firm_folder):
  logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))
      try:
          # get base path.
          io_path = settings.MEDIA_ROOT  #media root of firm
          print(io_path)
          credentials_path = os.path.dirname(__file__)
  
          print("\n\n\n", credentials_path, "\n", io_path)
  
          # Initial setup, create credentials instance.
          credentials = Credentials.service_account_credentials_builder() \
              .from_file(credentials_path + "/adobe_credentials/pdfservices-api-credentials.json") \
              .build()
  
          # Create an ExecutionContext using credentials and create a new operation instance.
          execution_context = ExecutionContext.create(credentials)
          extract_pdf_operation = ExtractPDFOperation.create_new()
  
          # Set operation input from a source file.
          source = FileRef.create_from_local_file(
              io_path + "/{firm_folder}/resources/{file_name}".format(
                  firm_folder=firm_folder, file_name=file_name), media_type = "application/pdf")
          # source = FileRef.create_from_stream(file_object,
          #                                     media_type="application/pdf")
          extract_pdf_operation.set_input(source)
  
          # Build ExtractPDF options and set them into the operation
          extract_pdf_options: ExtractPDFOptions = ExtractPDFOptions.builder() \
              .with_elements_to_extract([ExtractElementType.TEXT, ExtractElementType.TABLES]) \
              .with_element_to_extract_renditions(ExtractRenditionsElementType.TABLES) \
              .with_table_structure_format(TableStructureType.CSV) \
              .build()
          extract_pdf_operation.set_options(extract_pdf_options)
  
          # Execute the operation.
          result: FileRef = extract_pdf_operation.execute(execution_context)
  
          # Save the result to the specified location.
          result.save_as(io_path +
                         "/{firm_folder}/output/{file_name}.zip".format(
                             firm_folder=firm_folder, file_name=file_name))
```
Below is the traceback...
Since the traceback starts from the download_and_save method, can I presume that it was extracted successfully but encounters a problem when saving the zip file? I could really use some help, I posted the same issue on the adobe community a couple months ago but I got no response. Meanwhile, I used the Convert API which worked fine along with my custom code to get the table data, but now I really need this Extract API to get the tables as my custom code is insufficient to get the table data from certain pdfs.

```
INFO:adobe.pdfservices.operation.pdfops.extract_pdf_operation:All validations successfully done. Beginning ExtractPDF operation execution
ERROR:root:Exception encountered while executing operation
Traceback (most recent call last):
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\pdfops\extract_pdf_operation.py", line 134, in execute
    ExtractPDFAPI.download_and_save(location=location, context=execution_context, file_location=file_location)
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\internal\service\extract_pdf_api.py", line 52, in download_and_save
    response = CPFApi.cpf_status_api(location, context)
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\internal\api\cpf_api.py", line 91, in cpf_status_api
    response = polling2.poll(
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\polling2.py", line 191, in poll
    val = target(*args, **kwargs)
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\internal\api\cpf_api.py", line 92, in <lambda>
    lambda: http_client.process_request(http_request=http_request,
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\internal\http\http_client.py", line 41, in process_request
    if _handle_response_and_retry(response, success_status_codes,
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\internal\http\http_client.py", line 106, 
in _handle_response_and_retry
    raise OperationException(message="Error response received for request",
adobe.pdfservices.operation.internal.exceptions.OperationException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Django Projects\folder\root\pdf\extraction.py", line 97, in adobe_table_extract
    result: FileRef = extract_pdf_operation.execute(execution_context)
  File "C:\Users\user\Documents\Django Projects\folder\env\lib\site-packages\adobe\pdfservices\operation\pdfops\extract_pdf_operation.py", line 138, in execute
    raise ServiceApiException(message=oex.error_message, error_code=oex.error_code,
adobe.pdfservices.operation.exception.exceptions.ServiceApiException: description =ERROR - Unexpected error; requestTrackingId=AEdtMTKxZfgbgXdnwRzdISbrUVYcpRiY; statusCode=500; errorCode=UNKNOWN
```

**Comment by paras-n** [comment]
Hi @finch-wren, issues raised here should address problems in the samples for this repo. Closing this ticket.

Adobe community forum will be the appropriate place for the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
